# Tutorial on Python with respects to Machine Learning 
# www.python.org




In [1]:
# Object Oriented by nature 
#TensorFlow 
#Keras https://keras.io/ <has tutorials >
#Caffe 

#Using AWS - Amazon Machine Image 

SyntaxError: invalid syntax (<ipython-input-1-6433a14f9ad1>, line 5)

In [5]:
for i in range(4):
    print(i, end = ' ')

0 1 2 3 

In [7]:
for i in range(2, 6):
    print(i, end = ' ')
# range(Start, Stop, Step)

2 3 4 5 

In [9]:
# function 
def add(p,q,r):
    temp = p+q+r
    return temp

sum = add(1,10,100)
print(sum)

111


In [11]:
a, b, c = 1, 10, 100

def printsum():
    print(a + b +c)
    
printsum()

111


In [13]:
# lists or arrays 
a = [1, 2, 3]

print(a[0])  # index 

1


In [14]:
# mixed type of list

b = [1, True, a , 'four']
print(b)

[1, True, [1, 2, 3], 'four']


In [17]:
#slice of list
print(b[0:2])

[1, True]


In [20]:
def sum_and_diff(a,b):
    return[ a+ b, a-b]
x = sum_and_diff(7,4)
print(type(x))
print(x)
print(x[0])

<class 'list'>
[11, 3]
11


In [25]:
# dictionary note: curly braces 
ages = {'Tom': 32, 'Dick': 58, 'Harry':28}
print(type(ages))

for k in ages.keys():
    print(k, ages[k])
    
del ages['Tom']

ages['Bert'] = 49 

for k,v in ages.items():
    print(k,v)

<class 'dict'>
Tom 32
Harry 28
Dick 58
Harry 28
Dick 58
Bert 49


In [26]:
#Modules 

#spam.py
def fn():
    print('spam')
    
#eggs.py
def fn():
    print('eggs')


import spam 
import eggs

spam.fn()
eggs.fn()


from spam import fn
from eggs import fn as fn2

fn() # spam
fn2() # eggs

ImportError: No module named 'spam'

In [27]:
#context manager 

with open('spam.txt') as file:    # setup code
    for line in file:
        print(line, end=" ")      #teardown code 
        
        

FileNotFoundError: [Errno 2] No such file or directory: 'spam.txt'

In [48]:
# Apply to Keras 
import keras 
import numpy as np

a = np.array([1,2,3])
print(a)
print(a[0])

print(type(a))

a = np.array([[1,2,3],[4,5,6]])
print(a)

print(a.ndim)
print(a.size, a.shape, a.dtype)

print(np.arange(1, 25).reshape(2,3,4))

[1 2 3]
1
<class 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]]
2
6 (2, 3) int32
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [34]:
import numpy as np
import tensorflow as tf

FLAGS = None # default value 

def main(_): # _ special name - a place holder
    
    

SyntaxError: unexpected EOF while parsing (<ipython-input-34-9c0c60ef708d>, line 6)

In [49]:
#broadcasting

a = np.arange(9).reshape(3,3)
b = np.array([10,20,30])

print(a+b)

[[10 21 32]
 [13 24 35]
 [16 27 38]]
